name: pdgrapher
checkpoint: null
device: cuda

kwargs:
  mode: forward
  edge_index_path: null
  positional_features_dims: 16
  embedding_layer_dim: 64
  dim_gnn: 64
  n_layers_gnn: 2
  n_layers_nn: 2
  dropout: 0.1
  cell_set_len: 1
